import pytest

from scriptorium.domain import Artifact, Patch, PatchStatus, Verification, VerificationResult
from scriptorium.storage import Database

from ._factories import create_completed_attempt, make_run


def test_patch_verification_and_artifact_metadata(tmp_path) -> None:
    with Database(tmp_path / "state.sqlite3") as database:
        run = database.create_run(make_run())
        _, attempt = create_completed_attempt(database, run)
        artifact = database.add_artifact(
            Artifact(
                digest="e" * 64,
                relative_path="sha256/ee/" + "e" * 62,
                size=123,
                media_type="text/x-diff",
            )
        )
        patch = database.create_patch(
            Patch(
                run_id=run.id,
                base_commit=run.commit_sha,
                diff_digest=artifact.digest,
                summary="Clarify one sentence.",
                edits=({"path": "main.tex", "before": "old", "after": "new"},),
                attempt_id=attempt.id,
            )
        )
        database.decide_patch(patch.id, "approve", "Reviewed locally.")
        verification = database.create_verification(
            Verification(
                patch_id=patch.id,
                result=VerificationResult.PASS,
                summary="No regression found.",
            )
        )

        assert database.get_artifact(artifact.digest) == artifact
        assert database.get_patch(patch.id).attempt_id == attempt.id
        assert database.get_patch(patch.id).status == PatchStatus.VERIFIED
        assert database.list_verifications(patch.id) == [verification]
        applied = database.update_patch(patch.id, PatchStatus.APPLIED)
        assert applied.applied_at is not None


def test_patch_records_the_generating_attempt(tmp_path) -> None:
    with Database(tmp_path / "state.sqlite3") as database:
        run = database.create_run(make_run())
        _, attempt = create_completed_attempt(database, run)
        artifact = database.add_artifact(
            Artifact(
                digest="f" * 64,
                relative_path="sha256/ff/" + "f" * 62,
                size=10,
                media_type="text/x-diff",
            )
        )

        patch = database.create_patch(
            Patch(
                run_id=run.id,
                base_commit=run.commit_sha,
                diff_digest=artifact.digest,
                summary="Generated by one durable attempt.",
                edits=(),
                attempt_id=attempt.id,
            )
        )

        assert database.get_patch(patch.id).attempt_id == attempt.id


def test_new_patch_requires_a_generating_attempt(tmp_path) -> None:
    with Database(tmp_path / "state.sqlite3") as database:
        with pytest.raises(ValueError, match="generating attempt_id"):
            database.create_patch(
                Patch(
                    run_id="run_missing",
                    base_commit="a" * 40,
                    diff_digest="d" * 64,
                    summary="Missing provenance",
                    edits=(),
                )
            )
